apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{ include "helm.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`web4.lysmux.dev`)
      kind: Rule
      services:
        - name: {{ include "helm.fullname" . }}
          port: 3000
